### ISSUE TITLE
Payment method not showing on checkout

### ISSUE THREAD

**Issue by adamj88** [DividoFinancialServices/divido-magento#13]
I've installed the module and entered the API key however no Payment method associated with Divido is showing up at the checkout.

Do you have any idea as to why this may be?

**Comment by cjgk** [comment]
Hi,
We don't monitor this repo for support questions.
Please get in touch with our support team if you have questions regarding the use of this plugin.

**Comment by arun-js** [comment]
Hi,
Can I know how to get in touch with the support team? Thanks.
