### ISSUE TITLE
Divido Uninstallation

### ISSUE THREAD

**Issue by arun-js** [DividoFinancialServices/divido-magento#26]
Hi,
I wanted to uninstall the Divido Module from my magento 1 project but it creates some issues. I followed the procedure as described in the readme file. But once the plugin is uninstalled the "Add product" and "Edit Product" does not work. It shows an error page.

**Comment by JonnyCarter** [comment]
Hi Arun,

You need to double check that you have removed all files completely as outlined in the readme - and run the SQL commands  - being sure to remove/replace <prefix> depending on your installation. ie. 

`DROP TABLE divido_lookup;`
`DELETE FROM core_resource WHERE code = 'divido_pay_setup';`

Then you will want to make sure you have cleared the Magento cache, this is normally the step that fixes issues for me!

Please contact support@divido.com if you are having further issues.

**Comment by JonnyCarter** [comment]
Hi Arun -

I have updated the Readme to reflect another table that may have data in that needs to be cleared

Thanks for highlighting this

**Comment by arun-js** [comment]
Hi Jonathan,

Thanks for the help. Now it's working fine.
