### ISSUE TITLE
Uninstallation Error

### ISSUE THREAD

**Issue by bubblemedialtd** [DividoFinancialServices/divido-magento#27]
After completing the steps found in the readme, removing all files and performing the SQL queries, I am experiencing an issue.

When editing a product (any product that is), an exception is printed.

````
Source model "pay/source_option" not found for attribute "divido_plan_option"
`````

Please advise.

Magento 1.9.4

**Comment by JonnyCarter** [comment]
Hey Apologies on the delay to response here we do not actively monitor issues on this repository - all support requests go through our client support team https://www.divido.com/contact.

In this case it looks like the query to remove Divido from the eav_attribute table hasn't worked correctly for you!

`DELETE FROM eav_attribute where attribute_code LIKE '%divido%'`
May also be a prefixed table:
`DELETE FROM <prefix>eav_attribute where attribute_code LIKE '%divido%'

If you check in the database `eav_attribute` table for and option with that name `divido_plan_option ` and remove
